#define APM_IOC_PLLM_91 4
#define APM_IOC_PLLM_179 8
#define APM_IOC_USB_OFF 16
#define APM_IOC_USB_ON 32
#define APM_IOC_DDRSR_ON 64
#define APM_IOC_DDRSR_OFF 128
#define APM_IOC_PLLM_BYPASS 256
#define APM_IOC_PLLM_PLL 512
